version: '3.8'
services:
    nginx:
        image: bondiolino/nginx 
        hostname: nginx
        networks:
            msg-net:
                aliases:
                - nginx
networks:
  msg-net:
    external: true